### ISSUE TITLE
[Metadata] Expose data from bodymovin JSON (Markers, FrameCount, etc.) 

### ISSUE THREAD

**Issue by hinterlandcreative** [windows-toolkit/Lottie-Windows#100]
Implementations of lottie from other platforms allow playing animations based on a segment of the progress or a segment of frames. If `LottieVisualSource` had a `FrameCount` property we could at least convert frame based animations to progress based animations when using `Lottie-Windows` in a cross platform project.

**Comment by sohchatt** [comment]
Thanks for pointing out the need for frame information from the json. We're planning on addressing this issue in the next update. For the time being, a possible workaround might be to read that data directly from the JSON file itself; here's the schema for reference: https://github.com/airbnb/lottie-web/blob/master/docs/json/animation.json 

Do let us know if there's anything else that is blocking your adoption of Lottie-Windows.

**Comment by jaredhms** [comment]
I'm working on a ReactNative Windows LottieView implementation, and we need to have the frame rate exposed so we can convert from the app-specified start/end frames to their corresponding PlayAsync start/end progress percentage values.  

Exposing it off of these generated objects, or off of the AnimatedVisualPlayer itself would be great.

**Comment by simeoncran** [comment]
#206 surfaces FPS, duration in frames, and markers in comments in the generated code. Adding it to objects is coming.

**Comment by simeoncran** [comment]
@traore-i  Needs more clarity on what should be exposed, how it should be exposed, and differences between generated code vs LottieVisualSource.

**Comment by nishitha-burman** [comment]
Metadata exposed in generated code.
