### ISSUE TITLE
Linear and Radial Gradient Fills

### ISSUE THREAD

**Issue by FrayxRulez** [windows-toolkit/Lottie-Windows#115]
Do you have any plan to support gradients in the near future?

**Comment by sohchatt** [comment]
@FrayxRulez yes -- it's been on our wish-list but had no concrete customer requests until yours. Thanks for the feedback; we'll be sure to add it to the feature backlog.

**Comment by FrayxRulez** [comment]
I’ve actually worked on this over the weekend and I’ve fully implemented linear ones, would a PR be appreciated for them?

**Comment by sohchatt** [comment]
Absolutely!

**Comment by sohchatt** [comment]
Addressed by #123
