### ISSUE TITLE
Needs better handling of embedded content (e.g. embedded image)

### ISSUE THREAD

**Issue by plaiMS** [windows-toolkit/Lottie-Windows#116]

**Comment by sohchatt** [comment]
@plaiMS can you provide some additional context?

**Comment by plaiMS** [comment]
1) The C++ code gen can change to initialize byte[] inline instead of calling ref new.
2) LoadedImageSurface.StartLoadFromStream should take in an IRandomAccessStream instead of byte[]

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
