### ISSUE TITLE
Allow Lottie Viewer to display animations with Image Layers

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#119]
* consume .zip files to have access bundled assets
* default behavior for image layer with inaccessible asset
* generate appropriate warnings about file paths / permissions if necessary

**Comment by simeoncran** [comment]
Nice to have but priority isn't clear. @traore-i

**Comment by alex-harper** [comment]
We're working on a bundle format for [lottie](https://dotlottie.io/), and would like to be able to support this.

**Comment by simeoncran** [comment]
.lottie is the right way to solve this. As soon as LottieVisualSource can parse a .lottie file, we'll get this functionality for Lottie Viewer for free.

**Comment by simeoncran** [comment]
Lottie Viewer now displays images as long as they are embedded in the .json or the file is a .lottie file that contains the referenced images.
