### ISSUE TITLE
Lottie Viewer app crashes/ suspends on 19H1 Insider Preview builds

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#12]
The Lottie Viewer app crashes and certain animations throw exceptions on Windows 10 Insider Preview 18272 or greater. 

The underlying cause is a regression in the Windows.UI.Composition Animation APIs: the issue has been fixed, and should make its way to Insider Preview builds soon.

**Comment by michael-hawker** [comment]
It seems to be working for me on 18327.

**Comment by sohchatt** [comment]
closing since the fix made its way to insider flights (verified on 18327 above)
