### ISSUE TITLE
Investigate path direction + fill-rule

### ISSUE THREAD

**Issue by FrayxRulez** [windows-toolkit/Lottie-Windows#124]
The library has some issues with the rendering order for this animation.
Tried with a few other libraries (iOS, Android, Qt, Skia, Web) and they all process it correctly.
Tried quite hard to fix this by myself but I didn't succeed at all 😁 

Json file here:
[test_animation.json](https://github.com/windows-toolkit/Lottie-Windows/files/3208866/test_animation.txt)

Expected result:
![immagine](https://user-images.githubusercontent.com/8152849/58200485-27d93200-7cd3-11e9-9662-b286e4d3ba15.png)

Actual result:
![immagine](https://user-images.githubusercontent.com/8152849/58200523-40494c80-7cd3-11e9-8918-6c87d1f22073.png)

**Comment by sohchatt** [comment]
@FrayxRulez thanks for the bug report. Do you have the AEP file as well? Or any other lottie JSON files that also demonstrate the same incorrect behavior? 

Reducing these animations to a minimal repro is a struggle across all Lottie implementations at present.

**Comment by FrayxRulez** [comment]
I have a minimalized version of the same animation, with just head shape and eyes:
[minimal.json](https://github.com/windows-toolkit/Lottie-Windows/files/3215419/smaller.txt)

**Comment by simeoncran** [comment]
I see that we're painting in the wrong order, but I'm having trouble figuring out what the correct order should be. In your minimal.json, layer indexes are:
21 - shoulders
20 - head
25 - eye
26 - eye
Currently we draw in decreasing order of index, but doing that for minimal.json draws the eyes before the head. I'm wondering if maybe this isn't a problem with order, but with a mask or a matte or a blend or something that should allow the eyes to show through from behind. There's definitely something special about your file, I'm just not sure what it is yet!

Can you give me any more hints. Breaking it down further to just the head and the eyes would help although I can do that myself with some effort on the JSON. Even better would be an AEP of the minimalized JSON.

**Comment by NikhStash** [comment]
I am facing a similar problem
The following screenshots though might appear different are the same one from Web, other from Windows app.

Web
![Screenshot (47)](https://user-images.githubusercontent.com/26644187/60177334-47b1c780-9836-11e9-836a-20d4890c707c.png)

Windows
![Screenshot (46)](https://user-images.githubusercontent.com/26644187/60177337-497b8b00-9836-11e9-8c7c-a20a70230d51.png)

It works properly in Web, IOS and android.

**Comment by sohchatt** [comment]
@NikhStash thanks for the repro; will take a look.

**Comment by NikhStash** [comment]
In Web: (Expected Beahavior)
![Screenshot (47)](https://user-images.githubusercontent.com/26644187/63852456-ef25b480-c9b5-11e9-9a50-aa1d768180cc.png)


In Windows:
![Screenshot (46)](https://user-images.githubusercontent.com/26644187/63852452-ecc35a80-c9b5-11e9-9294-bd0dbffa97f5.png)

**Comment by NikhStash** [comment]
Are any steps being taken on this, if so any info on when this can be cleared!

**Comment by NikhStash** [comment]
Thanks, @sohchatt. It was not working in the previous build, but it is working perfectly in the latest build that you have specified.

**Comment by NikhStash** [comment]
> @NikhStash: I pushed the latest changes in master to the Lottie Viewer app a couple of days ago. Can you try it out? Your issue does not repro (even though your file results in warnings) / has been fixed.
> 
> The changes in master will be published in version 6.0, which should be released in about a month. (https://dev.azure.com/dotnet/WindowsCommunityToolkit/_build/results?buildId=20753&view=artifacts).


I have installed 6.0 version but it doesn't work. In this version, the screen is completely blank. It doesn't even show the faulted UI. Could you please share the working build again. And when can I expect a proper build.

**Comment by FrayxRulez** [comment]
I actually had to move away from this library and I made my own porting of [rlottie](https://github.com/Samsung/rlottie) using Win2D.

**Comment by NikhStash** [comment]
Actually @FrayxRulez  I was asking @sohchatt . Sorry for the confusion.
@sohchatt If you don't remember what I'm talking please refer: https://github.com/windows-toolkit/Lottie-Windows/issues/124#issuecomment-525809623

I have installed 6.0 version but it doesn't work. In this version, the screen is completely blank. It doesn't even show the faulted UI. Could you please share the working build again. And when can I expect a proper build.

**Comment by sohchatt** [comment]
@ajbennet / @scott-moore-ms / @simeoncran should be able to help you.

**Comment by ajbennet** [comment]
Thanks @sohchatt for looping us in. @NikhStash, we are looking into this. Will keep you posted as soon as we know. Thanks.

**Comment by NikhStash** [comment]
Thank you @ajbennet. Please let me posted.

**Comment by NikhStash** [comment]
@ajbennet any update on the issue.

**Comment by simeoncran** [comment]
@NikhStash this is working for me on the 6.1 preview code. Can you try it?

**Comment by simeoncran** [comment]
Closing this for now because I think this is working now. The original FrayxRulez issue has also been solved. This is still one remaining issue for the FrayxRulez file due to multiple animated, which we will work on separately. Please reopen if you are still seeing issues.

**Comment by simeoncran** [comment]
And the one remaining issue is fixed with: https://github.com/windows-toolkit/Lottie-Windows/pull/274.
