### ISSUE TITLE
Users running downlevel should get an issue when using unsupported features

### ISSUE THREAD

**Issue by eliezerpMS** [windows-toolkit/Lottie-Windows#126]
If a user builds LottieViewer with the latest Windows SDK but deploys to an older version of Windows and tries to use a feature in the latest Windows SDK, Lottie Windows should detect this scenario and log an issue which LottieViewer can then display.

**Comment by sohchatt** [comment]
Or, should any feature with dependencies on SDK version > 17763 report a warning? In that case, you get notified of the SDK dependency in LottieViewer but also via LottieGen. 

If yes, then this isn't a Lottie Viewer feature but a change required in the Translator for specific features ( such as Masks, Mattes, Radial Gradients, etc.)

**Comment by simeoncran** [comment]
Closing because this is done.
