### ISSUE TITLE
Can this library been used in .NET framework project?

### ISSUE THREAD

**Issue by Leon-Zhang** [windows-toolkit/Lottie-Windows#129]
I can run Lottie-Viewer which is based on Universal Windows;

I have a .NET framework based C# project, can I import dlls(under dlls folder) of this library to render lottie animations?

Thanks.

**Comment by simeoncran** [comment]
You can use [XAML Islands](https://channel9.msdn.com/Shows/Visual-Studio-Toolbox/XAML-Islands) to embed the AnimatedVisualPlayer into your .NET framework project.

BTW, the dlls built by the dlls folder only exist to enforce modularity of the project - we don't expect them to be used (although you could use them if they were useful to you!).

**Comment by Leon-Zhang** [comment]
@simeoncran Thanks for reply.
Could you provide sample project for reference? I have used XAML Island and can using UWP namespace in csharp, but in xaml file still says AnimatedVisualPlayer does not exists in namepsace Windows.UI.Xaml.Controls; Same error for lottie:LottieVisualSource type.

**Comment by michael-hawker** [comment]
@Leon-Zhang just came across this thread, `AnimatedVisualPlayer` is part of [WinUI](https://aka.ms/winui).
