### ISSUE TITLE
Issues with Store Certification regarding Lottie package

### ISSUE THREAD

**Issue by Leisvan** [windows-toolkit/Lottie-Windows#135]
Hi.
My last submission to the store failed because of a WACK failure. The issue seems to be related to the Microsoft.Toolkit.UWP.UI.Lottie package. Previous submission referenced this package and had no problem, though this is my first submission targeting 1903 and min version 1809. Here is the error they sent me:

Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

**Comment by sohchatt** [comment]
@Leisvan thanks for bringing this to our attention. Are you using the latest stable version of WinUI and the 5.1.1 for Lottie?

**Comment by Leisvan** [comment]
Not sure right now. At the moment I was using the latest versions.

**Comment by sohchatt** [comment]
So did you manage to submit to the store eventually?

**Comment by Leisvan** [comment]
Nope. I added some WinUI components to my app, had to roll back the changes after the error.

**Comment by hippieZhou** [comment]
When I tried to submit my app, I found that validation failed，as followd:

![Snipaste_2019-11-12_17-39-02](https://user-images.githubusercontent.com/13598361/68660092-7de8ad00-0573-11ea-8e2a-95c8ed32aa64.png)

![Snipaste_2019-11-12_17-40-47](https://user-images.githubusercontent.com/13598361/68660146-95279a80-0573-11ea-8d77-df6d5ace357a.png)

Can you tell me what should I do?

**Comment by sohchatt** [comment]
@hippieZhou does this issue persist even if you're on Microsoft.UI.Xaml release version 2.2?

**Comment by hippieZhou** [comment]
@skendrot , When I use  Microsoft.UI.Xaml release version 2.2, this issue didn't persist, But I have a new issue, as follows:
![Snipaste_2019-11-15_11-04-05](https://user-images.githubusercontent.com/13598361/68913854-b2d54980-0797-11ea-9e3d-c0ec028ebc41.png)

may I have your help?

**Comment by dpaulino** [comment]
@hippieZhou you can ignore that error. It's a known bug in the WACK tool. See this thread: https://github.com/microsoft/microsoft-ui-xaml/issues/1446

**Comment by hippieZhou** [comment]
@dpaulino ,Yeah，Thanks for your help.

**Comment by dpaulino** [comment]
@Leisvan I upgraded to the pre-release version of WinUI and that seemed to solve my WACK issues regarding the IDynamicAnimatedVisualSource. Here's the link to the prerelease package: https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.3.191123003-prerelease

Have doing that?

**Comment by Leisvan** [comment]
Thanks @dpaulino I'll try that later.

**Comment by sohchatt** [comment]
Seems like the underlying issue has been fixed based on the conversation that @dpaulino linked to. Feel free to re-open if it persists.
