### ISSUE TITLE
RepeatCount

### ISSUE THREAD

**Issue by sumitsahoo** [windows-toolkit/Lottie-Windows#140]
Please give an option to set RepeatCount. Currently I am not able to stop looping animation. Currently the port gives an option to do just that : [Lottie Port GitHub](https://github.com/azchohfi/LottieUWP). Since this is the official version there should be a similar option as well.

**Comment by sohchatt** [comment]
Thanks for your feedback about adding a RepeatCount parameter to AnimatedVisualPlayer's PlayAsync method.

In the meanwhile, you can achieve the same result with a few lines of code:

In your XAML, set the Player's AutoPlay property to False:
```xaml
<controls:AnimatedVisualPlayer x:Name="LottiePlayer" AutoPlay="False">
     <lottie:LottieVisualSource x:Name="LottieJsonSource" UriSource="ms-appx:///AnimatedVisuals/LottieLogo1.json"/>
</controls:AnimatedVisualPlayer>
```
And in your code-behind, you may create a helper method as follows:
```cs

private async Task PlayWithRepeatCountAsync(int count)
{
    for (int i=0; i<count; i++)
    {           
        await _player.PlayAsync(fromProgress:0, toProgress:1, looped:false);
    }
}
```

For more information about the PlayAsync method, feel free to check out [this page](https://docs.microsoft.com/windows/communitytoolkit/animations/lottie-scenarios/async_play). Do let us know if this solved your problem.

**Comment by sumitsahoo** [comment]
Well this seems like a great solution but a XAML option would be nice too :) Maybe in future release :)

**Comment by vincentcastagna** [comment]
@sumitsahoo why this issue has been closed ? Every lottie packages provides this functionnality ([Xamarin BaseFlow](https://github.com/Baseflow/LottieXamarin), Flutter, Angular ...). We need to play with `PlayAsync` in code behind which adds a lot of code for such a simple prop.
