### ISSUE TITLE
Version 1803 (OS build 17134) Support ?

### ISSUE THREAD

**Issue by sumitsahoo** [windows-toolkit/Lottie-Windows#141]
Can it run on Version 1803 (OS build 17134) ? Some devices get update way later. Just a thought. Any suggestion ?

**Comment by sohchatt** [comment]
Lottie-Windows is currently only supported for the October 2018 Update (17763) and above. 

This problem of versioning is expected to be solved by WinUI 3.0, which will enable Lottie-Windows (and the rest of the WindowsUI platform) to run on earlier versions of the OS. For more information and questions about WinUI 3.0, see [this thread](https://github.com/microsoft/microsoft-ui-xaml/issues/717).

In the meanwhile, one temporary solution may be to use traditional media formats such as Images or Gifs via the FallbackContent property for versions < 17763 as [shown here](https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/fallback).

**Comment by sumitsahoo** [comment]
Thanks for the information. Waiting for WinUI, it really sounds great.
