### ISSUE TITLE
[MacOS]  Can lottie-windows support debugging under MacOS system?

### ISSUE THREAD

**Issue by TernenceHsu** [windows-toolkit/Lottie-Windows#158]
If I installed  _.NET Core 3.0_  and  _Visual Studio Code_  on a MacOS system, can I also use it to debug lottie-windows?

**Comment by sohchatt** [comment]
If you're running Lottie-Windows in your application, the presumption is that it's a Windows application. Lottie-Windows animations rely on Windows Runtime (WinRT) components; so, they can only be rendered on Windows 10.0.17763 and above.
