### ISSUE TITLE
Add support for Image layer (JSON)

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#167]
This builds upon #118 to enable LottieVisualSource to parse an image file. We need to ensure access to the asset folder: this feature may involve adding a new set of APIs that allows a developer to speciy the URI or source from where the assets may be retrieved.

**Comment by simeoncran** [comment]
@traore-i  - figure out priority

**Comment by simeoncran** [comment]
This is fixed now. LottieVisualSource has a property to set an image asset resolver. In addition, if the Lottie file is in the .lottie format and the referenced images are in the .lottie file then images will be displayed form them.
