### ISSUE TITLE
Support color + opacity animations on the same object

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#172]
Currently, opacity is pushed to down to the ARGB values in the brush at the leaf nodes (except for PreComp Layers which are their own Visual and therefore have a .Opacity property). This leads to the limitation that both color and opacity cannot be animated on the same animation because WinComp doesn't support targeting individual channels in the Color struct in the expression language. The way to work around this limitation is a fairly large change that represents all Color values as a Vector4 + expressions.  

See: https://github.com/windows-toolkit/Lottie-Windows/blob/warningPages/source/Issues/LT0015.md

**Comment by simeoncran** [comment]
This works in 6.1.
