### ISSUE TITLE
Support gradient + opacity animations on the same object

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#173]
An extension of #172, this would enable gradients to benefit from its stops having their color and opacity animated. In the worst case, this could mean that the colorstop + opacitystop + opacitytransform are all individually animated and target the same CompositionGradientColorStop (the supported cases might need some scoping). 

Currently, the work around is to isolate any object that needs its gradient and its opacity animated to a Precomp layer.

**Comment by simeoncran** [comment]
This is done in 6.1
