### ISSUE TITLE
Add Cpp support for LottieVisualSource

### ISSUE THREAD

**Issue by jaredhms** [windows-toolkit/Lottie-Windows#175]
We have a React Native app that we are porting to React Native Windows (vNext), written primarily in C++ and React -- no .NET framework pulled into the process.  We've wrapped an implementation of LottieAnimationView around an AnimatedVisualPlayer, but we must first generate code for all of our animations via LottieGen.  The requirement for code gen is problematic for several reasons:

1. We can never upstream our LottieAnimationView to the community as an official ReactNative Windows implementation, because it requires a lot of extra configuration and code gen to use with existing applications.

2. We have to special-case our LottieViews with code like this, because our LottieAnimationView 
 implementation needs to get the **_name_** of a .json file so it can load the correct generated component, whereas other platforms expect to get the actual .json contents.  It also makes it difficult/impossible to honor the 'imageAssetsFolder' property.

export const BACKGROUND_ANIMATION_SOURCE = Platform.select({
    windows: './starryBg.json',
    default: require('./starryBg.json'),
});

            <LottieView
                source={BACKGROUND_ANIMATION_SOURCE}
                imageAssetsFolder={'lottie/Home'}
                autoPlay
                loop
                resizeMode="cover"
                hardwareAccelerationAndroid
                style={{ position: 'absolute', top: 0, left: 0, width, height }}
            />

**Comment by simeoncran** [comment]
@traore-i  to figure out priority and resourcing.

**Comment by nishitha-burman** [comment]
Hello,

Currently there are no plans to convert LottieVisualSource to cpp.
