### ISSUE TITLE
Crash on .cs animation playback start after 6.0.0 upgrade - in Debug builds

### ISSUE THREAD

**Issue by achipa** [windows-toolkit/Lottie-Windows#205]
Branch: rel/6.0.0
Build environment: VS2017 15.9.18
OS: Win10 1909 x64

I had an animation I generated/used with 5.1.1, but kept crashing after upgrading to 6.0.0 through nuget. I thought at first it's the .cs that was somehow broken/incompatible, but then I built the official Lottie-Viewer (as it hasn't been updated in ages in the store) and realized it crashes the same way on startup, even with it's own default welcome LottieLogo.cs animation.

Steps to reproduce:
1. Check out rel/6.0.0
2. Open solution in VS
3. Rebuild-all (Debug, x86)
4. Start LottieViewer

Expected: 
LottieViewer starts

Actual:
LottieViewer crashes in LottieLogo.cs with 

```
Exception thrown: 'System.IO.FileNotFoundException' in LottieViewer.exe
An exception of type 'System.IO.FileNotFoundException' occurred in LottieViewer.exe but was not handled in user code
The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

...in LottieLogo.cs, while invoking `CanvasPathBuilder`

```cs
            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-13.6639996F, -0.144999996F));
                    builder.AddLine(new Vector2(75.663002F, 0.289999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }
```

![image](https://user-images.githubusercontent.com/822934/70672863-c613f180-1c3d-11ea-8fea-488a7463bd6a.png)

The same crash happens with all .cs animations as they all have the `CanvasPathBuilder` invocation. The same .cs works/plays back fine on 5.1.1.

**Comment by simeoncran** [comment]
Hey @achipa , I'm not seeing this issue here. The CanvasPathBuilder is part of Win2D and the error is complaining about a module, so that makes me think that something is up with your Win2D NuGet. Win2D should be getting included in your app, so you might want to look at the output directory of the app and see if it's there.

To see what an app is looking for and failing to find at runtime, I usually use SysInternals ProcMon https://docs.microsoft.com/en-us/sysinternals/downloads/procmon. Can you use that and see exactly what it's failing to find?

**Comment by achipa** [comment]
@simeoncran Well, it's a bit inconclusive, at least to my rather rudimentary procmon skills. To make this even more interesting, setting the build to *release* makes it go away, so it seems to be looking for something debug related (maybe release/debug requirements fell out of sync?).

Procmon logs of crash attached (to be clear - this is not a 3rd party app, this is the LottieViewer UWP within this very project).

[LottieViewer_Logfile.zip](https://github.com/windows-toolkit/Lottie-Windows/files/4021266/LottieViewer_Logfile.zip)

**Comment by simeoncran** [comment]
@achipa that log suggests that the system can't find VCRUNTIME140_1_APP.dll.
Just before the end of the log, the process looks in various places for that dll but doesn't find it.

Is that enough of a hint to track down the issue?

If not let me know and I'll dig deeper. In the meantime, can you confirm that the problem repros when you clone and build in a fresh directory?

**Comment by achipa** [comment]
@simeoncran Yes, fresh clones exhibit the same behavior. 

Now, looking a bit at that DLL it seems that this dependency mismatch might be related somehow to VS2019 indirectly. There are parts of the solution (like LottieGen) that explicitly say they need dotnetcore 3.1, which in turn needs VS2019. Now, I'm not sure if it's just Lottie-Viewer getting bitrotten/out of sync (ie should it also be a VS2019 only project), or that VS2017 that I'm trying to build it with that gets confused somehow, if that makes any sense.

**Comment by simeoncran** [comment]
@achipa did you get this figured out? I'm going to close this for now because I haven't heard back form you and nobody else it reporting the issue. Feel free to reactivate the issue.

I do suggest only using VS2019 as we never try to test it on VS2017.
