### ISSUE TITLE
Visibility problem

### ISSUE THREAD

**Issue by KSemenenko** [windows-toolkit/Lottie-Windows#232]
Found a strange bug, I have several Lottie controls, one on top of the other, for different animations of a "single visual object".
and I noticed that after the animation was played, and I decided to hide the player, it still remains visible on the screen.
that is, from an invisible state, the player becomes visible.
then I play the animation. and I want to hide the player, but it remains visible.

**Comment by simeoncran** [comment]
How do you hide the player? Any chance can you share a simple UWP project that demonstrates the problem?

**Comment by KSemenenko** [comment]
I use this library https://github.com/Baseflow/LottieXamarin, and now I working on new renderer for UWP wich will use Lottie-Windows. and  in paralell I check it in my project.
I was trying to set Visibilty to Callapsed in renderer, and anyway control is still appeared.

**Comment by KSemenenko** [comment]
I think the problem looks like this.
1. the item is not visible
2. The item becomes visible.
3. play animation
4. the item should become not visible
5. the item still remains on the screen

**Comment by KSemenenko** [comment]
hmm, seems it's not visibility issue
