### ISSUE TITLE
UWP não funciona se compilado com cadeia de ferramenta .net nativo

### ISSUE THREAD

**Issue by ortizbnu** [windows-toolkit/Lottie-Windows#241]
Olá,

Alguem já passou por isto ?

Lottie funciona bem **se não estiver marcado para compilar com cadeia de ferramenta .net nativo**.

Porém marcando a opção ( no meu caso para publicação na windows store preciso marcar) **ele não funciona ficando em branco.**

![Compilar-01](https://user-images.githubusercontent.com/47483268/74059636-2c5f8b00-49c7-11ea-97e9-5ceef63cbc58.png)

![Com- net_nativo](https://user-images.githubusercontent.com/47483268/74060042-e48d3380-49c7-11ea-87de-265795b8debf.png)
![Sem- net_nativo](https://user-images.githubusercontent.com/47483268/74060044-e525ca00-49c7-11ea-9a0f-ab13081b09e5.png)

**Comment by simeoncran** [comment]
Por favor, desculpe minha falta de português. Estou usando o Google tradutor para poder responder no seu idioma.

Oi @ortizbnu. Isso ainda se reproduz para você? Não estou vendo esse problema com o Lottie Viewer (que é compilado com o .NET Native e está na loja).

---
English:
Please excuse my lack of Portugese. I'm using Google translate so I can reply in your language.

Hi @ortizbnu. Does this still repro for you? I'm not seeing this issue with Lottie Viewer (which is compiled with .NET Native and is in the store).

**Comment by simeoncran** [comment]
Closing this for now. Please reopen with more info if this is still reproing.
