### ISSUE TITLE
Add support for Text layer

### ISSUE THREAD

**Issue by achipa** [windows-toolkit/Lottie-Windows#245]
Support for Text Data (and Text layers in general) would be really nice

https://github.com/airbnb/lottie-web/wiki/Text

The benefits over just rendering glyphs:
1. Language agnostic text (content/strings can be localized at load time)
2. Size - glyphs result in considerably larger files

**Comment by simeoncran** [comment]
@traore-i - need to figure out priority.

**Comment by Timon-iRS** [comment]
@simeoncran, do you have any updates about this task, cuz` I would be appreciated if your team will implement this feature?

**Comment by nishitha-burman** [comment]
Hello,

Currently there are no plans to support text on Lottie-Windows.
