### ISSUE TITLE
Is Lottie-Windows compatible with Xamarin.Forms UWP projects?

### ISSUE THREAD

**Issue by sjorsmiltenburg** [windows-toolkit/Lottie-Windows#252]
could anybody here answer my question on stackoverflow?
https://stackoverflow.com/questions/61446769/are-lottie-animations-supported-in-xamarin-forms-uwp-projects?noredirect=1#comment108709450_61446769

**Comment by jamesmcroft** [comment]
Although you've already found it, it's probably worth closing this off. 

It is supported through the [LottieXamarin](https://github.com/Baseflow/LottieXamarin) library which uses this. But there did appear to be an issue with it which I think I've resolved 👍
