### ISSUE TITLE
NuGet package description is not descriptive

### ISSUE THREAD

**Issue by chingucoding** [windows-toolkit/Lottie-Windows#253]
The package description for Microsoft.Toolkit.Uwp.UI.Lottie is just "Package Description". Instead this package should have a meaningful package description. See screenshot below:

![unknown](https://user-images.githubusercontent.com/16122379/81154387-222c3900-8f84-11ea-92d2-8e6fe2ccf444.png)

**Comment by jamesmcroft** [comment]
Should be a simple fix too, just some missing csproj metadata that needs adding in here - https://github.com/windows-toolkit/Lottie-Windows/blob/master/Lottie-Windows/Lottie-Windows.csproj

**Comment by simeoncran** [comment]
This won't show up until the 6.1 release (soon!)
