### ISSUE TITLE
App Submission to store & WACK Fails when using Lottie.

### ISSUE THREAD

**Issue by avknaidu** [windows-toolkit/Lottie-Windows#258]
When using Lottie Version 6.0.0 WACK Fails. Also If you submit the app to store it fails with same reason. See below,

![image](https://user-images.githubusercontent.com/6171200/81956490-ffa3bb00-9628-11ea-9d4d-72c2c0a8a51b.png)

**Comment by simeoncran** [comment]
@avknaidu  - we are looking into this right now. Lottie Viewer and our Lottie Samples apps are both in the store and they reference these types. We have noticed WACK issues locally in the past but they weren't causing problems on store submissions. Can you share any more information about your app? E.g. what language is it using. Are you using the AnimatedVisualPlayer? What version of WinUI are you using? IAnimatedVisual is defined in WinUI, so maybe all that's missing is the WinUI nuget.

**Comment by avknaidu** [comment]
@simeoncran Please see below 
WinUI 2.4
Yes I am using AnimatedVisualPlayer to load LottieFiles.
Targeting latest version of Windows SDK.

However even if I downgrade WinUI to 2.3 its same.

**Comment by simeoncran** [comment]
@avknaidu  - we've not been able to repro the issue which means we're flying blind. Can you provide any more information, or even better could you zip up a simple project that demonstrates the problem?

**Comment by avknaidu** [comment]
@simeoncran Will do. By tomorrow.

**Comment by ajbennet** [comment]
@avknaidu : Were you able to reproduce this issue? If not, I d like to close this issue. Thanks.

**Comment by avknaidu** [comment]
@ajbennet I am closing this issue for now because I do not have my dev system available with me at-least for few more weeks. If i have this issue in future, i will reopen it.

**Comment by ajbennet** [comment]
We were able to do a local repro of this issue and we are looking at it. Please track this using this issue #214 https://github.com/windows-toolkit/Lottie-Windows/issues/214
