### ISSUE TITLE
lottie issues/warnings html page

### ISSUE THREAD

**Issue by sohchatt** [windows-toolkit/Lottie-Windows#30]
1. Generate the list of known parsing and translation issues as an html page (builds from the source)
2. Host the resulting page in this repo
3. Update uri in LottieViewer's Issues section with the correct link
4. Update store submission to reflect this change

**Comment by simeoncran** [comment]
@sohchatt  - someone (aka you) has to fill in the the description, remarks, and resources for the .sources/Issues/*.md files.

**Comment by simeoncran** [comment]
I've filled in the docs.
