### ISSUE TITLE
Tracking issue: Replace Lottie-Windows sample with new XAML Controls Gallery Sample

### ISSUE THREAD

**Issue by chingucoding** [windows-toolkit/Lottie-Windows#304]
This is a tracking issue for [this](https://github.com/microsoft/Xaml-Controls-Gallery/issues/441#issuecomment-651419807) (by @simeoncran)

Once https://github.com/microsoft/Xaml-Controls-Gallery/pull/480 is finished and approved, I'll port the changes over here.

**Comment by simeoncran** [comment]
@ajbennet - Changing this will require changing the MSDN page that documents it. https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/playback. Also the proposed changes align our code with what Xaml Controls Gallery apparently wants, but it hides the Stop concept and maybe isn't appropriate for the samples. What do you think?
See also: https://github.com/microsoft/Xaml-Controls-Gallery/pull/480

**Comment by chingucoding** [comment]
I've updated the button to look like a stop button now, and the behavior didn't change much.

**Comment by simeoncran** [comment]
Copy-paste from the PR:

I'm rejecting this PR now, but @chingucoding you should definitely push back the improvements from the CR to XCG.
The reasons for rejecting here are that, as much as this makes the playing sample more interesting, it also makes it more complicated and that replaces some concepts that are fundamental to the Lottie API with higher level concepts. Also, having discussed this with @stmoy, I've come to the conclusion that it's actually good to have XCG diverge from the samples here. XCG enables discovery and inspiration, whereas the samples here are about getting people started on the fundamental concepts.
Apologies @chingucoding for encouraging you down this path then switching on you, but it took me some time to realize how this should fit.
