### ISSUE TITLE
Need clear how-to for C++ devs.

### ISSUE THREAD

**Issue by simeoncran** [windows-toolkit/Lottie-Windows#323]
C++ devs that follow our docs may think they need LottieVisualSource then will get confused when it talks about needing the CLR. We should have clear docs for people who use no C#.

**Comment by nishitha-burman** [comment]
https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/json_codegen describes the workflow for doing this in C++ and C#.
