### ISSUE TITLE
Load animation from memory

### ISSUE THREAD

**Issue by under3415** [windows-toolkit/Lottie-Windows#333]
Instead of loading animation from a storage file or a URI, is it possible to load it from memory? Either a string or a memory buffer of some sort?

Some scenarios where this would be useful:
- JSON stored in a database
- JSON files encrypted to protect IP
- JSON files compressed to save on disk space or reduce number of files on disk for deployment

**Comment by nishitha-burman** [comment]
P2
There is already a PR for this
Dev Cost: Half a day

**Comment by simeoncran** [comment]
Fixed with #341
