### ISSUE TITLE
IsAnimatedVisualSourceDynamic should default to false

### ISSUE THREAD

**Issue by simeoncran** [windows-toolkit/Lottie-Windows#340]
When LottieGen generates code for a Lottie file that references external images, it adds a property called IsAnimatedVisualSourceDynamic to the generated code. This defaults to true, and causes the animated visual to not complete loading until its images have all completed loading. If IsAnimatedVisualSourceDynamic is set to false, the Lottie will load synchronously and images will pop in as they load.

Having a default of true seems to have caused a lot of confusion (see https://github.com/microsoft/microsoft-ui-xaml/issues/1484) so I think we're better off making it false by default.

**Comment by nishitha-burman** [comment]
P2
Dev Cost: Half a day

**Comment by simeoncran** [comment]
Fixed with #346
