### ISSUE TITLE
Theming could use HTML classes

### ISSUE THREAD

**Issue by simeoncran** [windows-toolkit/Lottie-Windows#347]
Lottie for web and BodyMovin support annotations on names that allow you to define HTML classes and ids. Some people use that for doing color theming on the web. Lottie-Windows has it's own syntax based on CSS for doing color theming. Lottie-Windows could also use HTML classes as a way of identifying fills and strokes that have the same color so that designers could use classes in both web and Lottie-Windows.

See https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
