### ISSUE TITLE
Support TimeStretch

### ISSUE THREAD

**Issue by simeoncran** [windows-toolkit/Lottie-Windows#383]
After Effects allows layers to be given a time stretch factor. This seems to be just a factor to multiply their times by. One use I've seen is to reverse the direction of a layer (TimeStretch = -1).

Note that a time-stretched layer could be anywhere in a chain of layers (i.e. it could be in a parent layer), so during translation the stretching factor would need to be passed around in the context, and every frame value (e.g. in-point, out-point, key frames) would need to be adjusted.

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
