### ISSUE TITLE
App manifest validation error after update to visual studio 2019 16.8.0

### ISSUE THREAD

**Issue by steam3d** [windows-toolkit/Lottie-Windows#384]
After update to visual studio 2019 16.8.0 I get the error while project build. (I use lottie animation in my app. I did not change manifest etc. I installed Microsoft.Toolkit.Uwp.UI.Lottie many month ago and it worked perfect.)

`Error   APPX0501    Validation error. error 80080204: App manifest validation error: Line 191, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource" must only be declared once. A duplicate exists on Line 78, Column 27.   SampleApp C:\PathTo\AppxManifest.xml`

I tried to clean solution and rebuild it did not help. I have a pc with VS 16.7.7, my app builds without any problem on it.

**Comment by simeoncran** [comment]
This is tough with no other information. I don't know what is causing this, but please try removing all the obj and bin directories in your project and let me know if that helps. If it doesn't, please find the AppxManifest.xml and share it with me. Even better, share the project with me and I'll investigate further.

**Comment by steam3d** [comment]
I deleted obj and bin nothing changed. I tried to delete all folders **.vs** also nothing change. Then i just deleted the whole project and cloned it from remote repository and everting works now.

**Comment by simeoncran** [comment]
Good to hear you got this solved!
