### ISSUE TITLE
Lottie CodeGen for WinUI 3

### ISSUE THREAD

**Issue by Marv51** [windows-toolkit/Lottie-Windows#396]
The branch certainly looks good 🤩.

Please keep working on it and ship a preview of LottieGen for WinUI.

**Comment by simeoncran** [comment]
That wish has already been granted: https://www.nuget.org/packages/LottieGen/7.0.0-preview4

**Comment by Marv51** [comment]
Don't know how I missed that 🥳🥳🥳🥳
