### ISSUE TITLE
Windows Store App Certification Fails after upgrading Microsoft.UI.XAML to v2.5.0

### ISSUE THREAD

**Issue by under3415** [windows-toolkit/Lottie-Windows#405]
Hi
I am using Microsoft.Toolkit.Uwp.UI.Lottie v.6.1.0 and Microsoft.UI.Xaml. 

After I updated Microsoft.UI.Xaml from 2.5.0-prerelease201202003 to the v.2.5.0 (release) the app got rejected from the store with the following errors. This was the only change to the app, was all good with pre-release UI.Xaml

**FAILED**
    General metadata correctness

    Error Found: The general metadata correctness test detected the following errors:
        Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
        The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

        Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
        The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

**Comment by under3415** [comment]
Same thing after upgrading Lottie to to v.7.0.0-preview4

**Comment by nishitha-burman** [comment]
Hi @under3415,

Thank you for reaching out, we are investigating this issue.

**Comment by nishitha-burman** [comment]
Hi @under3415,

Have you tried this: https://github.com/windows-toolkit/Lottie-Windows/issues/214#issuecomment-699094690

**Comment by under3415** [comment]
Forgot about that one, I'll try that, thanks! The issue was fixed in pre-release, but resurfaced in v2.5.0. 
BTW I've also logged it here and they seem to know the root cause: https://github.com/microsoft/microsoft-ui-xaml/issues/3298

**Comment by under3415** [comment]
> 
> 
> Hi @under3415,
> 
> Have you tried this: [#214 (comment)](https://github.com/windows-toolkit/Lottie-Windows/issues/214#issuecomment-699094690)?

Hi
Yep that worked! Thanks
D

**Comment by under3415** [comment]
Actually, the workaround didn't work. It was accepted for a "test flight", but not for a production release. 
So below workaround did not work.
https://github.com/windows-toolkit/Lottie-Windows/issues/214#issuecomment-699094690

**Comment by nishitha-burman** [comment]
Hi @under3415,

We are investigating the issue.

**Comment by nishitha-burman** [comment]
Hi @under3415,

We are still investigating the issue, apologies for the wait. Are you able to use the pre-release version until there is a fix?

**Comment by under3415** [comment]
Hi
Thanks for the update!

Yes, I am using **Microsoft.Toolkit.Uwp.UI.Lottie 7.0.0-preview4** with **Microsoft.UI.Xaml 2.5.0-prerelease.201202003** for now. That is working and being accepted by the store. 

Regards

**Comment by under3415** [comment]
I have installed the latest Microsoft.UI.Xaml v.2.6.0-prerelease210129001 and that works with Microsoft.Toolkit.Uwp.UI v7.0.0-preview4

**Comment by nishitha-burman** [comment]
@under3415 thank you for the update and glad it works! I will go ahead and close this issue. Please reopen this issue if other problems come up. Thank you!

**Comment by under3415** [comment]
Hi
This is again an issue with the latest versions of UI XAML and Lottie:

- Microsoft.UI.XAML 2.6.0-prerelease.210405001
- Microsoft.Toolkit.Uwp.UI.Lottie v7.0.2

> Error Found: The general metadata correctness test detected the following errors:
> 
>     Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
>     The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
>     Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
>     The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

**Comment by under3415** [comment]
@nishitha-burman  can you please re-open this issue, I don't have permissions?

**Comment by nishitha-burman** [comment]
Hi @under3415,

Thank you for reaching out. We will take a look.

**Comment by under3415** [comment]
Hi, 
Another RTM release, another store rejection! 

I have updated Microrsoft.UI.Xaml to 2.6.0 and my app got rejected by the store (in test flight). There were no other changes. Unfortunately, the store no longer gives any details, just says "failed certification". There is no report :-( 

![image](https://user-images.githubusercontent.com/3857822/124190503-7d20d800-db16-11eb-9200-c4b86e859d9e.png)

Cert App on PC does not detect any issues. 

Help please!

**Comment by nishitha-burman** [comment]
Hi @under3415, 

Thank you for reaching out! What version of Lottie-Windows are you using?

**Comment by under3415** [comment]
Hi
7.0.3. Below are all the packages in my solution

![image](https://user-images.githubusercontent.com/3857822/124191108-6929a600-db17-11eb-9c82-16a2b07b9246.png)

**Comment by under3415** [comment]
Note that this is also raised with Win.UI. 
https://github.com/microsoft/microsoft-ui-xaml/issues/3780

**Comment by nishitha-burman** [comment]
I see, thank you. We are looking into this.

**Comment by nishitha-burman** [comment]
@under3415 it might also be related to this issue we are investigating: https://github.com/microsoft/microsoft-ui-xaml/issues/5298

**Comment by nishitha-burman** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/5298 is tracking the issue.
