### ISSUE TITLE
[Feature Request] Release xcopy-compatible exe

### ISSUE THREAD

**Issue by aschultz** [windows-toolkit/Lottie-Windows#410]
**Rationale**

Developers often have the need for their dependencies to be versioned specifically to the codebase they're currently working on. Globally-installed tools are problematic if the developer needs to switch between repos or branches that depend on different versions. A standalone exe would allow each repo to manage its own toolchain independently and avoids the need to install additional dependencies, such as .NET Core.

**Comment by simeoncran** [comment]
I agree. The dotnet global tools makes little sense now. We should package a .NET 5 single-file app. https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

**Comment by simeoncran** [comment]
This is in master now. There is a new Nuget package called LottieGen.MsBuild that contains an MsBuild task that will allow you to run LottieGen in msbuild. Currently only available for x64, but that's probably what everyone needs right now anyway.
