### ISSUE TITLE
Cannot compile generated .cs file

### ISSUE THREAD

**Issue by bigbendk** [windows-toolkit/Lottie-Windows#414]
[Diamonds.json.txt](https://github.com/windows-toolkit/Lottie-Windows/files/5860194/Diamonds.json.txt)

[Diamonds.cs.txt](https://github.com/windows-toolkit/Lottie-Windows/files/5860197/Diamonds.cs.txt)

Hi,

I am trying to include a lottie animation, but I am having problems compiling the generated .cs file from lottiegen.

Input and output files are attached.

When generating the CS file, I get these warnings, but it does output the file.

LottieGen.exe -inp "C:\Users\x\Desktop\Comp1\Diamonds.json" -L cs -o "C:\Users\x\Desktop\Comp1\CS"
Lottie for Windows Code Generator version 7.0.0-build.92+gfe7369a6e1

Reading file:
 C:\Users\x\Desktop\Comp1\Diamonds.json
**C:\Users\x\Desktop\Comp1\Diamonds.json: warning LP0017: Unexpected field: l.
C:\Users\x\Desktop\Comp1\Diamonds.json: warning LP0017: Unexpected field: ReadAnimatableVector3.l.**
C# code for class Diamonds written to:  C:\Users\x\Desktop\Comp1\CS\Diamonds.cs

The viewer shows the file just fine, but shows the same warnings.

When compiling in my UWP app, I get these compiler errors:
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Graphics.Canvas.Geometry.CanvasGeometry' to 'Windows.Graphics.IGeometrySource2D'	X		Controls\Diamonds.cs	283	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Graphics.Canvas.Geometry.CanvasGeometry' to 'Windows.Graphics.IGeometrySource2D'	X		Controls\Diamonds.cs	289	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Graphics.Canvas.Geometry.CanvasGeometry' to 'Windows.Graphics.IGeometrySource2D'	X		Controls\Diamonds.cs	297	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Graphics.Canvas.Geometry.CanvasGeometry' to 'Windows.Graphics.IGeometrySource2D'	X		Controls\Diamonds.cs	303	Active

I am compiling with VS2019, UWP application, set to minimum Windows ver. 1903

Any thoughts on this?

**Comment by simeoncran** [comment]
Do you get this problem with the official build (in the nuget https://www.nuget.org/packages/LottieGen/6.1.0)?
And are you including the Win2D nuget package?

**Comment by bigbendk** [comment]
I did not have the Win2D Nuget package installed. Installing that solved the problem. 
Thank you @simeoncran !
