### ISSUE TITLE
PathKeyFrameAnimation runtime version test prevents animated paths on Windows 10 20H2.

### ISSUE THREAD

**Issue by simeoncran** [windows-toolkit/Lottie-Windows#418]
The Windows PathKeyFrameAnimation class is broken on all versions of Windows before 20H2. See https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.pathkeyframeanimation?view=winrt-19041

Lottie-Windows checks the UAP version at runtime to determine whether PathKeyFrameAnimations can be used, but the check isn't accurate. It checks that the UAP version is at least 11, however the UAP version didn't get incremented for 20H2. Right now animated paths get turned off by Lottie-Windows on 20H2 even though they are safe to use.

Testing the UAP version is not sufficient. We need to test something else. Perhaps the Windows version number will suffice, or maybe there is some other feature that changed in UWP for 20H2 that we can test for.

**Comment by nishitha-burman** [comment]
Lottie-Windows is handling this issue correctly.
