### ISSUE TITLE
Big delay in debug to instantiate AnimatedVisualPlayer

### ISSUE THREAD

**Issue by ArchieCoder** [windows-toolkit/Lottie-Windows#436]
I copied the exact same code from the LottieViewer sample regarding the method RunAnimatedSplashScreenAsync.

As you see in the screenshot, even without adding any source, the control takes 4 seconds to instantiate. I cannot repro anywhere else and in release it works well.

It is just a show stopper in debug. In the Performance profiler, the time used in is "Window Resized", but it does not say anything.

![image](https://user-images.githubusercontent.com/1608424/113441213-e54b0b00-93bb-11eb-9afb-a297e0f81074.png)

**Comment by nishitha-burman** [comment]
Hi @ArchieCoder,

Thank you for reaching out. Which version of Lottie and WinUI are you using?

**Comment by ArchieCoder** [comment]
@nishitha-burman Hi, after more digging, there is a problem that is either Windows or app system. If you work only with Lottie, you can close the issue, but if you are working on a broader area, please have a look at my global issue:

https://developercommunity.visualstudio.com/t/UWP-5s-Delay-launching-the-app-in-debu/1392780?port=1026&fsid=9997be04-e828-4053-b1cf-87e70b64c588&entry=suggestion&ref=native&refTime=1618251085000&refUserId=fc4e9a04-225c-449f-9725-72970fd5e284

**Comment by nishitha-burman** [comment]
Thanks for the update, I will close this issue since it is not a Lottie-Windows issue. Seems like your global issue has been triaged, hope that gets resolved soon!
