### ISSUE TITLE
Why are the projects using shared code files?

### ISSUE THREAD

**Issue by hansmbakker** [windows-toolkit/Lottie-Windows#5]
While building the code I this repo I noticed there are several “shared files” projects being used - can you explain why you chose to do that?

**Comment by simeoncran** [comment]
Hi Hans. The shared files are about packaging and enforcing modularity. 

We package the code into 3 different binaries: the Lottie-Windows nupkg, the LottieGen command line tool, and the Lottie Viewer app. While we could have the LottieGen and Lottie Viewer consume the Lottie-Windows nuget, that would require an extra step, and in the case of LottieGen it would require an extra binary to be copied around.

Modularity is enforced by building the code as a set of dlls. This allows the compiler to enforce modularity boundaries, e.g. to ensure that WinCompData.dll doesn't accidentally take a dependency on internal details of LottieData.dll, and that dependencies between the dlls are acyclic. The dlls are never expected to be consumed by any product. It's really a workaround for C#/.NET having assemblies as the only way of expressing this type of modularity.

**Comment by hansmbakker** [comment]
Thank you for your explanation!
