### ISSUE TITLE
Publish Lottie Viewer and Lottie Samples in the Microsoft Store under the Microsoft publisher name

### ISSUE THREAD

**Issue by hansmbakker** [windows-toolkit/Lottie-Windows#51]
Are you aware that somebody put the [lottie viewer in the Microsoft Store](https://www.microsoft.com/store/productId/9P7X9K692TMW)? Is it official?

**Comment by azchohfi** [comment]
Yes, that is the official one.

**Comment by azchohfi** [comment]
The author is @sohchatt

**Comment by hansmbakker** [comment]
Ah, excuse me.

However, to avoid confusion, would you consider releasing it under the Microsoft name as is the case with other developer tools as well?

Examples are [Fluent Xaml Theme Editor](https://www.microsoft.com/store/productId/9N2XD3Q8X57C) and [Xaml Studio](https://www.microsoft.com/store/productId/9NTLS214TKMQ).

**Comment by simeoncran** [comment]
It's planned. @sohchatt did this to get it out quickly. There's some approval process or something that Sohum is pushing through to make it Microsoft branded.

**Comment by hansmbakker** [comment]
Good to hear, keep up the good work :)

**Comment by sohchatt** [comment]
@mevey: reopening this issue and assigning it you. Let me know when you're ready to publish Lottie Viewer and Lottie Samples using the Microsoft publisher name in the Store and I'll remove the current submissions. 

Note: We'll need to ensure that aka.ms urls (/lottieviewer and /lottiesamples) are appropriately redirected as well.

**Comment by simeoncran** [comment]
@ajbennet  did this already. The aka.ms urls should be pointing to the right place as we managed to change the owner without creating a new app id. However they're broken, so I'll create an issue for that.
