### ISSUE TITLE
Lottie Viewer App Buttons aren't Narrator Accessible

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Lottie-Windows#52]
All the buttons in the app aren't readable by Narrator.

**Comment by sohchatt** [comment]
Thanks for reporting. We should certainly fix this. Labeling appropriately to solicit community help.

**Comment by simeoncran** [comment]
@traore-i Can you figure out what exactly is needed to satisfy this. Which buttons, and what they should be reporting to narrator.

**Comment by simeoncran** [comment]
Reopening because #310 fixed the sample app, but not the Lottie Viewer.
