### ISSUE TITLE
Readme should have more info on how to get started

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Lottie-Windows#55]
The readme is a little sparse at the moment.  It should have more details on how to use the library.  For instance:

- [x] Link to the Lottie Viewer app to install
- [x] Tell me the nuget package I need (have the command I can copy and paste to add it to my project)
- [ ] Show me a snippet of XAML that I can copy and paste in and modify the source uri

**Comment by sohchatt** [comment]
Addressed in #65 -- feel free to reopen if the new readme updates prove to be insufficiently helpful. Feedback is always appreciated!
