### ISSUE TITLE
LottieGen should have -Version

### ISSUE THREAD

**Issue by azchohfi** [windows-toolkit/Lottie-Windows#63]
... or version should be displayed when you run `LottieGen -Help`.

The only other way to know the version of LottieGen is when you run `dotnet tool list -g`.

**Comment by simeoncran** [comment]
The version is there in the first line. Not sure what you're seeing, so please re-open with a repro and the output you get.

C:\Users\simeonc>lottiegen -help
Lottie for Windows Code Generator version 5.0.0-build.37+gd3810b27b1

**Comment by azchohfi** [comment]
I tested this with a previous preview version that didn't have this. My bad.
