### ISSUE TITLE
Create a Visual Studio extension to support the import of Lottie files into a project

### ISSUE THREAD

**Issue by jamesmcroft** [windows-toolkit/Lottie-Windows#86]
There's a good use case for having a Visual Studio extension that replicates the functionality that the command line tool and LottieViewer can do so additional tooling isn't required in order to import a Lottie file into your Visual Studio project.

Looking at how this extension might look, it feels like the best user experience would be a right-click -> add where you would choose the JSON file and the output file would be automatically added to your project, ready to use.

**Comment by simeoncran** [comment]
We need to define exactly what this would do. And what the priority is.

**Comment by simeoncran** [comment]
It would good if there was a way to just click on something and get the LottieGen stuff added to the solution. It would include the latest LottieGen.exe and targets files that would run LottieGen automatically during build.

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
