### ISSUE TITLE
Request: provide Explorer plugin 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#90]
As the title says.
It will make it easier to understand the content of the files.

I mean that it will view Lottie files as thumbnails, something like this one that works for SVG:
https://www.maketecheasier.com/view-svg-thumbnails-windows-explorer/

**Comment by sohchatt** [comment]
This feature is not in our near-term plans at the moment. However, we're happy to accept PRs if you'd like to add this functionality.

**Comment by AndroidDeveloperLB** [comment]
Sorry but I don't have the experience and knowledge for developing such a thing for Windows.

**Comment by AndroidDeveloperLB** [comment]
Please do consider adding it though.
