### ISSUE TITLE
Request: allow to browse and search in Lottie-files website within the app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#93]
Maybe show as gallery.

**Comment by sohchatt** [comment]
It appears that lottiefiles.com needs authentication for users to browse through animations. Closing for now because this doesn't align with Lottie Viewer's priorities.

**Comment by AndroidDeveloperLB** [comment]
Why add it? Why not allow all to reach those, like normal websites... ?
