### ISSUE TITLE
Request: offer trimming/cropping 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#95]
Allows to trim/crop the animation and export to a new file.

**Comment by simeoncran** [comment]
This is out of scope for Lottie Viewer. Lottie Viewer is not a tool for editing. Editing should be done in After Effects. After Effects can import a Lottie file.

**Comment by AndroidDeveloperLB** [comment]
@simeoncran Sadly After Effects isn't free, isn't for developers, and is quite bloated.
Lottie files are something that we can all use and download freely from various places (when allowed).
